version: '2.1'

volumes:
  geoserver-data:

services:
  geoserver:
    container_name: geoserver
    build:
      context: .
      #args:
        #GS_VERSION: 2.14.1
        #ORACLE_JDK: "false"
        #COMMUNITY_MODULES: "true"
        #TOMCAT_EXTRAS: "true"
    image: geoserver:2.14.1
    #volumes:
    #  - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8600:8080"
    #restart: on-failure
    #env_file:
    #  - docker-env/geoserver.env
